---
- name: Create Tomcat user
  become: yes
  user:
    name: tomcat
    state: present
- name: Create a Tomcat Group
  group:
    name: tomcat
- name: Create Tomcat directory
  become: yes
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755
    owner: tomcat
    group: tomcat
- name: Download Tomcat
  become: yes
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz
    dest: /opt/tomcat
    mode: 0755
    remote_src: yes
    group: tomcat
    owner: tomcat
    extra_opts: [--strip-components=1]
- name: Create Tomcat service file
  become: yes
  copy:
    content: |-
      [Unit]
      Description=Apache Tomcat
      After=network.target
      
      [Service]
      Type=forking
      
      Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
      Environment="CATALINA_HOME=/opt/tomcat/"
      Environment="CATALINA_BASE=/opt/tomcat/"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      
      User=tomcat
      Group=tomcat
      UMask=0007
      RestartSec=10
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/tomcat.service
- name: Start and Enable Tomcat
  become: yes
  ansible.builtin.systemd_service:
    name: tomcat
    daemon_reload: true
    state: started
    enabled: true
- name: Open Port
  become: yes
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled